// packages/core/src/errors/generation/generation-error-codes.ts

export const GENERATION_ERROR_CODES = {
  GENERATION_CANCELLED: 'GENERATION_CANCELLED',

  INVALID_OUTPUT_PATH: 'INVALID_OUTPUT_PATH',

  EMPTY_TEMPLATE: 'EMPTY_TEMPLATE',

  TEMPLATE_NOT_FOUND: 'TEMPLATE_NOT_FOUND',

  FILE_WRITE_FAILED: 'FILE_WRITE_FAILED',
} as const;

export type GenerationErrorCode =
  (typeof GENERATION_ERROR_CODES)[keyof typeof GENERATION_ERROR_CODES];
