export const VALIDATION_ERROR_CODES = {

    INVALID_GENERATOR_DEFINITION:
        'VALIDATION_INVALID_GENERATOR_DEFINITION',

    DUPLICATE_OUTPUT_PATH:
        'VALIDATION_DUPLICATE_OUTPUT_PATH',

    MISSING_TEMPLATE_VARIABLE:
        'VALIDATION_MISSING_TEMPLATE_VARIABLE'

} as const


export type ValidationErrorCode =
    typeof VALIDATION_ERROR_CODES[
    keyof typeof VALIDATION_ERROR_CODES
    ]